services:
  build-image:
    image: nes-game
    build: .
  build-nes:
    image: nes-game
    command: sh -c "make clean && make"
    depends_on:
    - build-image
    volumes:
    - ./:/workdir
