name: main-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: build and export Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: nes-game # needs to match Docker compose
          outputs: type=docker,dest=/tmp/myimage.tar
      - name: upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: myimage.tar
          path: /tmp/myimage.tar
          retention-days: 1
  build-nes:
    runs-on: ubuntu-latest
    needs: build-image
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage.tar
          path: /tmp
      - name: load downloaded Docker image
        run:  docker load --input /tmp/myimage.tar
      - name: build nes file
        run:  docker compose run --rm build-nes
      - name: upload nes file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-nes-file
          path: build/game.nes
      - name: remove Docker image artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: myimage.tar
