name: main-workflow

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build-nes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: determine short GIT hash
        id:   vars
        run:  echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: build docker image
        run:  docker compose build
      - name: build nes file
        run:  docker compose run --rm build-nes
      - name: upload nes file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.vars.outputs.sha_short }}-nes-file
          path: build/game.nes
